#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l vmem=12000mb
#PBS -l walltime=24:00:00
#PBS -o /storage/home/eyvorchuk/nobackup/logs/reverse_lats
#PBS -e /storage/home/eyvorchuk/nobackup/errors/reverse_lats
#PBS -m ae
#PBS -N reverse_lats_PNWNAmet_pr

module load cdo-bin
file=/storage/data/projects/dataportal/data/vic-gen2-forcing/PNWNAmet_pr.nc
base=$(basename $file)

echo "$(date) Copying $base to $TMPDIR"
cp $file $TMPDIR

echo "$(date) Reversing latitudes for $base"
cdo invertlat $TMPDIR/$base $TMPDIR/invert_lat_$base

echo "$(date) Moving $base with reversed latitudes to original location"
mv $TMPDIR/invert_lat_$base /storage/data/projects/dataportal/data/vic-gen2-forcing/invert_lat_$base

echo "$(date) Granting write permissions to staff for $base with reversed latitudes"
chmod g+w /storage/data/projects/dataportal/data/vic-gen2-forcing/invert_lat_$base
