name: Docker Publishing

on:
  push:
    branches:
      - '*'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  publish-test-ncwms-speed:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.pcicdevops_at_dockerhub_username }}
          password: ${{ secrets.pcicdevops_at_dockerhub_password }}
          dockerfile: ./actions/test_ncWMS_speed/docker/Dockerfile
          repository: pcic/test-ncwms-speed
          tag_with_ref: true
