#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l vmem=12000mb
#PBS -l walltime=24:00:00
#PBS -o /storage/home/eyvorchuk/nobackup/logs/assoc_ensemble_PRISM/
#PBS -e /storage/home/eyvorchuk/nobackup/errors/assoc_ensemble_PRISM/
#PBS -m ae
#PBS -N PRISM_assoc_ensemble

database='postgresql://pcic_meta:PASSWORD@db.pcic.uvic.ca:5433/pcic_meta'
venv=/storage/home/eyvorchuk/code/modelmeta
cd $venv
source venv/bin/activate

#indir=/storage/data/climate/observations/gridded/PRISM
#for file in $indir/*CAI*.nc
indir=/storage/data/climate/observations/gridded/PRISM/split_climos
for file in $indir/*19910101*.nc
do
    base=$(basename $file)
    ensemble=bc_prism_monthly_and_climos
    echo "$(date) Associating $base with $ensemble"
    python scripts/associate_ensemble -n $ensemble -v 1 -d $database $file
done
